[package]
name = "shiki-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../README.md"
description = "shiki: pure logic (notebooks, notes, git, search, templates)"

[dependencies]
serde.workspace = true
serde_yaml.workspace = true
chrono.workspace = true
regex.workspace = true
git2.workspace = true
nucleo-matcher.workspace = true
thiserror.workspace = true
tracing.workspace = true
self_update.workspace = true
tempfile.workspace = true
pulldown-cmark.workspace = true
age.workspace = true
