[package]
name = "shiki-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../README.md"
description = "shiki: TUI interface (ratatui)"

[dependencies]
shiki-core.workspace = true
shiki-config.workspace = true
ratatui.workspace = true
crossterm.workspace = true
ratatui-textarea.workspace = true
comrak.workspace = true
syntect.workspace = true
two-face.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
base64.workspace = true
unicode-width.workspace = true
directories.workspace = true
arboard.workspace = true
png.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
tempfile.workspace = true
